### ISSUE TITLE
Create Documentation of the REST interface

### ISSUE THREAD

**Issue by Korkmatik** [E-Edu/task#1]
# Description
We have to document our provided interfaces so other teams know how to use them.

# Suggestion
- Maybe we could create a PDF with LATEX. It is also possible to versionate this file with git.
- Or we could just use Markdown files for this?

**Comment by steve-hb** [comment]
I would suggest to write Swagger documentation. It doesn't have to be too detailed, but its an industry standard.

**Comment by steve-hb** [comment]
Since we have a specialized team for rest documentation, I'll close this
