### ISSUE TITLE
Return all tasks that a user has created

### ISSUE THREAD

**Issue by Korkmatik** [E-Edu/task#23]
# Description

According to the [spec](https://github.com/E-Edu/draft-documents/blob/master/endpoints/task.md#task-1) it should be possible to get all tasks that a user has created.

# Suggestion

- "authorId" is an attribute in the "Task"-Table. So it should be possible to get all tasks by the author id
- This interface needs the author ID which is a GUID according to the "User Microservice Team"
- This interface should return all tasks created by the specified user

**Comment by PAException** [comment]
blocked by #127

**Comment by PAException** [comment]
Could be combined with #185
