### ISSUE TITLE
Support pagination

### ISSUE THREAD

**Issue by Korkmatik** [E-Edu/task#88]
# Description

Support pagination

**Comment by steve-hb** [comment]
We need for every route returning arrays something like this: (skip: X, max: Y)
By implementing these variables we can provide database-supported pagination.

**Comment by PAException** [comment]
What should we Use? 

https://www.baeldung.com/hibernate-pagination

**Comment by steve-hb** [comment]
https://www.baeldung.com/spring-data-jpa-pagination-sorting
